---
abstract: 'A small, lightweight profiler for time and memory as Plack middleware'
author:
  - 'Colin Kuskie <colink@plainblack.com>'
build_requires:
  HTTP::Request::Common: 0
  Log::Any::Test: 0
  Plack::Builder: 0
  Plack::Test: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.013, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-Middleware-LightProfile
requires:
  Log::Any: 0
  Process::SizeLimit::Core: 0
  Time::HiRes: 0
version: 0.002
